stages:
  - check
  - deploy

server:
  stage: check
  image: python:3.10
  script:
    - cd server
    - pip install -r requirements.txt
  rules:
    - changes:
        - server/**/*

deploy:
  stage: deploy
  image: alpine
  before_script:
    - apk add openssh-client sshpass
  script:
    - chmod +x scripts/deploy.sh
    - scripts/deploy.sh
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'
      when: never
    - changes:
        - server/**/*
