# Generated by Django 4.0.5 on 2022-06-13 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="family",
            name="members",
            field=models.ManyToManyField(
                related_name="families", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
