# Generated by Django 4.0.5 on 2022-06-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_family_members"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="family",
            options={"verbose_name_plural": "Families"},
        ),
    ]
