# Generated by Django 4.0.5 on 2022-06-19 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_family_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "token",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.family"
                    ),
                ),
            ],
        ),
    ]
