import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { brandDark, nativeDark } from "../src/colors";

/**
 * Emits the Wear OS app's color constants from the shared dark palette, so the
 * watch can't drift from the brand the way a hand-copied hex list would.
 *
 * Wear is dark-only: a watch face is dark, ambient mode is dark, and a light
 * theme on an OLED panel is a battery cost for nothing. The one deliberate
 * departure from `nativeDark` is `background`, forced to pure black — black
 * pixels are *off* pixels on OLED, and it's the platform convention. The Suro
 * brown survives as the surface/card color, so the app still reads as Suro.
 */

const __dirname = dirname(fileURLToPath(import.meta.url));

const OUTPUT = join(
  __dirname,
  "../../../apps/wear/app/src/main/java/dev/clotet/suro/wear/ui/theme/Color.kt",
);

/** Wear OLED convention: the page behind everything is off, not dark brown. */
const WEAR_BACKGROUND = "#000000";

/**
 * Wear Material3 `ColorScheme` slots, mapped onto the shared palette. Named
 * after the Compose properties they feed so `Theme.kt` is a plain 1:1 wiring.
 */
const WEAR_COLORS = {
  primary: brandDark.primary,
  onPrimary: brandDark.background,
  primaryContainer: brandDark.primaryLight,
  onPrimaryContainer: brandDark.text1,
  secondary: brandDark.accent,
  onSecondary: brandDark.background,
  secondaryContainer: nativeDark.navBar,
  onSecondaryContainer: brandDark.text1,
  tertiary: brandDark.text3,
  onTertiary: brandDark.background,
  tertiaryContainer: nativeDark.card,
  onTertiaryContainer: brandDark.text1,
  background: WEAR_BACKGROUND,
  onBackground: brandDark.text1,
  surfaceContainerLow: nativeDark.card,
  surfaceContainer: nativeDark.bg,
  surfaceContainerHigh: nativeDark.navBar,
  onSurface: brandDark.text1,
  onSurfaceVariant: brandDark.text2,
  outline: brandDark.stroke,
  outlineVariant: nativeDark.inputBg,
  error: brandDark.error,
  onError: brandDark.background,
  errorContainer: nativeDark.card,
  onErrorContainer: brandDark.error,
} as const satisfies Record<string, string>;

/** Extra brand colors Wear's ColorScheme has no slot for. */
const EXTRA_COLORS = {
  suroSuccess: brandDark.success,
  suroMarker: brandDark.accent,
} as const satisfies Record<string, string>;

/** `#RRGGBB` -> the `0xFFRRGGBB` literal Compose's `Color(...)` wants. */
function toComposeLiteral(hex: string): string {
  const value = hex.replace("#", "").toUpperCase();
  if (!/^[0-9A-F]{6}$/.test(value)) {
    throw new Error(`Expected an opaque #RRGGBB color, got "${hex}"`);
  }
  return `0xFF${value}`;
}

function declaration([name, hex]: [string, string]): string {
  const capitalized = name.charAt(0).toUpperCase() + name.slice(1);
  return `val ${capitalized} = Color(${toComposeLiteral(hex)})`;
}

export function generateWearColorsKt(): string {
  const scheme = Object.entries(WEAR_COLORS).map(declaration).join("\n");
  const extra = Object.entries(EXTRA_COLORS).map(declaration).join("\n");
  return `package dev.clotet.suro.wear.ui.theme

import androidx.compose.ui.graphics.Color

// GENERATED by packages/design-tokens/scripts/generate-wear-colors.ts.
// Do not edit by hand — run \`pnpm --filter design-tokens generate\`.

${scheme}

${extra}
`;
}

mkdirSync(dirname(OUTPUT), { recursive: true });
writeFileSync(OUTPUT, generateWearColorsKt());
console.log(
  "Wrote apps/wear/app/src/main/java/dev/clotet/suro/wear/ui/theme/Color.kt",
);
