version: '3'

services:
  api:
    build: .
    ports:
      - 8000:8000
    environment:
      - DB_USER=familia
      - DB_PASSWORD=familia
      - DB_NAME=familia
      - DEBUG='True'
      - SECRET_KEY=django-insecure-tc=hna@#b6i)-!w#a&^pv^(scvsngz5li^$kylj3j+4)p_h=fj
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  
  db:
    environment:
      - POSTGRES_USER=familia
      - POSTGRES_PASSWORD=familia
      - POSTGRES_DB=familia
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
