plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'dev.clotet.suro'
version = '0.1.0'

android {
  namespace "expo.modules.surowear"
  defaultConfig {
    versionCode 1
    versionName '0.1.0'
  }
}

dependencies {
  implementation "com.google.android.gms:play-services-wearable:19.0.0"
  implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2"
  implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2"
  // Turns the Wearable Task APIs into suspend calls.
  implementation "org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.10.2"
}
