# Generated by Django 4.0.5 on 2022-06-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0002_rename_complete_listitem_is_complete_list_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="list",
            name="name",
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
