# Generated by Django 4.0.5 on 2022-06-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0003_alter_list_description_alter_list_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listitem",
            options={"ordering": ["is_complete", "order"]},
        ),
        migrations.AddField(
            model_name="listitem",
            name="order",
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
