# Generated by Django 4.0.5 on 2022-06-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0004_alter_listitem_options_listitem_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="is_favorite",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
