# Generated by Django 4.0.5 on 2022-06-14 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0005_list_is_favorite"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="list",
            options={"ordering": ["-is_favorite", "-updated_at"]},
        ),
    ]
