# Generated by Django 4.0.5 on 2022-06-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0006_alter_list_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listitem",
            name="order",
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
