# Generated by Django 4.0.5 on 2022-06-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0007_alter_listitem_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="listitem",
            name="category",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
