# Generated by Django 4.0.5 on 2022-06-19 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0008_listitem_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listitem",
            options={"ordering": ["category", "is_complete", "order"]},
        ),
    ]
