# Generated by Django 4.0.5 on 2023-02-15 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0009_alter_listitem_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listitem",
            options={"ordering": ["category", "is_complete", "order", "id"]},
        ),
    ]
