package dev.clotet.suro.wear.ui.theme

import androidx.compose.ui.graphics.Color

// GENERATED by packages/design-tokens/scripts/generate-wear-colors.ts.
// Do not edit by hand — run `pnpm --filter design-tokens generate`.

val Primary = Color(0xFFA3BC8D)
val OnPrimary = Color(0xFF211A16)
val PrimaryContainer = Color(0xFF2B231D)
val OnPrimaryContainer = Color(0xFFF3ECDF)
val Secondary = Color(0xFFE0A066)
val OnSecondary = Color(0xFF211A16)
val SecondaryContainer = Color(0xFF2B231D)
val OnSecondaryContainer = Color(0xFFF3ECDF)
val Tertiary = Color(0xFFA3BC8D)
val OnTertiary = Color(0xFF211A16)
val TertiaryContainer = Color(0xFF19120E)
val OnTertiaryContainer = Color(0xFFF3ECDF)
val Background = Color(0xFF000000)
val OnBackground = Color(0xFFF3ECDF)
val SurfaceContainerLow = Color(0xFF19120E)
val SurfaceContainer = Color(0xFF211A16)
val SurfaceContainerHigh = Color(0xFF2B231D)
val OnSurface = Color(0xFFF3ECDF)
val OnSurfaceVariant = Color(0xFFA0968F)
val Outline = Color(0xFF40362F)
val OutlineVariant = Color(0xFF332C28)
val Error = Color(0xFFEF8278)
val OnError = Color(0xFF211A16)
val ErrorContainer = Color(0xFF19120E)
val OnErrorContainer = Color(0xFFEF8278)

val SuroSuccess = Color(0xFF7AE088)
val SuroMarker = Color(0xFFE0A066)
